#! /usr/bin/env ruby
# frozen_string_literal: true

# (C) Wei Chen (willsmile)
# MIT license

require "goldman"

begin
  Goldman::Cli.new(ARGV).run
rescue Goldman::Error => ex
  warn "ERROR: #{ex}"
  exit 1
end
